'use strict';

const CONFIG = Object.freeze({
  canvasWidth: 1100, canvasHeight: 720, boardColumns: 10, tileSize: 52, tileGap: 8,
  diceMin: 1, diceMax: 6, farmMinRoll: 3, resortBonusMove: 2, resortChance: 0.25,
  hotelRerolls: 1, casinoLuckBonus: 2, bankMoneyBonusRate: 0.2, harborIncomeBonusRate: 0.15,
  startHP: 55, startAttack: 10, startDefense: 3, startLuck: 1, startMoney: 260,
  boardMin: 25, boardMax: 40, branchMin: 2, branchMax: 3, bossDamageTurns: 10,
  guardReduction: 0.5, bossAttackVariance: 3, minDamage: 1, innHeal: 28, innCost: 35,
  shopItemCost: 45, potionHeal: 25, powerPlantItemChance: 0.35, laboratoryAttackBonus: 1,
  eventGoodLuckTarget: 4, eventHeal: 12, eventDamage: 8, moneyTileReward: 45, treasureMin: 50,
  treasureMax: 120, warpMaxBack: 4, startRegion: 0, firstSpace: 0, logLimit: 8,
  rankSS: 70, rankS: 90, rankA: 115, rankB: 145, rankC: 180,
  scoreAssetDivisor: 1000, scoreIncomeDivisor: 100, scoreBossBonus: 8,
  assetOwnedMultiplier: 1, finalBossIndex: 4, uiButtonStart: 0, uiButtonHeight: 36, uiButtonGap: 8, frameRate: 30, randomInclusiveOffset: 1,
  hudX: 20, hudY1: 30, hudY2: 55, hudY3: 80, boardX: 20, boardY: 110, textPad: 8, tileTextY: 28, propertyTextY: 650, messageTextY: 680, uiImageX: 940, uiImageY: 18, uiImageW: 110, uiImageH: 40, rankX: 780, rankY: 80,
  colors: Object.freeze({ bg: '#0f172a', text: '#f8fafc', muted: '#94a3b8', player: '#facc15', danger: '#ef4444' }),
  tileWeights: Object.freeze({ Town: 7, Shop: 3, Event: 5, Treasure: 3, Inn: 3, Money: 4, Warp: 2, Branch: 2 }),
  categories: Object.freeze(['Agriculture', 'Food', 'Industry', 'Commerce', 'Special']),
  tileTypes: Object.freeze(['Town', 'Shop', 'Event', 'Treasure', 'Inn', 'Money', 'Warp', 'Branch', 'Boss']),
  regions: Object.freeze([
    Object.freeze({ name: 'Green Valley', boss: Object.freeze({ name: 'Debt Goblin', hp: 45, attack: 8, defense: 2 }) }),
    Object.freeze({ name: 'Port City', boss: Object.freeze({ name: 'Market Kraken', hp: 58, attack: 10, defense: 3 }) }),
    Object.freeze({ name: 'Iron Hills', boss: Object.freeze({ name: 'Steel Ogre', hp: 72, attack: 12, defense: 4 }) }),
    Object.freeze({ name: 'Sky Resort', boss: Object.freeze({ name: 'Luxury Phoenix', hp: 86, attack: 14, defense: 5 }) }),
    Object.freeze({ name: 'Capital Core', boss: Object.freeze({ name: 'Monopoly Dragon', hp: 105, attack: 16, defense: 6 }) })
  ]),
  properties: Object.freeze([
    Object.freeze({ name: 'Farm', category: 'Agriculture', price: 120, income: 32, passive: 'Minimum die roll becomes 3.', description: 'Stable harvests reduce bad movement turns.' }),
    Object.freeze({ name: 'Orchard', category: 'Agriculture', price: 150, income: 38, passive: 'Events heal HP on good outcomes.', description: 'Fruit gifts improve risky encounters.' }),
    Object.freeze({ name: 'Ranch', category: 'Agriculture', price: 180, income: 48, passive: 'Restores HP after boss victory.', description: 'Supplies recovery between regions.' }),
    Object.freeze({ name: 'Ramen Shop', category: 'Food', price: 130, income: 34, passive: 'Inns heal extra HP.', description: 'Warm meals make recovery efficient.' }),
    Object.freeze({ name: 'Restaurant', category: 'Food', price: 170, income: 45, passive: 'Bad events are softened.', description: 'Hospitality turns disasters manageable.' }),
    Object.freeze({ name: 'Cafe', category: 'Food', price: 110, income: 28, passive: 'Gain money after guarding.', description: 'Small comfort improves defensive turns.' }),
    Object.freeze({ name: 'Factory', category: 'Industry', price: 210, income: 62, passive: 'Shop prices are discounted.', description: 'Mass production lowers item costs.' }),
    Object.freeze({ name: 'Steel Mill', category: 'Industry', price: 240, income: 70, passive: 'Gain defense before boss fights.', description: 'Better equipment reduces damage.' }),
    Object.freeze({ name: 'Power Plant', category: 'Industry', price: 260, income: 78, passive: 'Chance to generate a potion each turn.', description: 'Energy infrastructure creates supplies.' }),
    Object.freeze({ name: 'Hotel', category: 'Commerce', price: 220, income: 68, passive: 'One reroll per region.', description: 'Travel planning fixes poor dice.' }),
    Object.freeze({ name: 'Theme Park', category: 'Commerce', price: 230, income: 74, passive: 'Money tiles pay more.', description: 'Tourism boosts direct cash.' }),
    Object.freeze({ name: 'Hot Spring', category: 'Commerce', price: 190, income: 55, passive: 'Heal slightly at turn start.', description: 'Passive recovery supports long routes.' }),
    Object.freeze({ name: 'Resort', category: 'Commerce', price: 250, income: 80, passive: 'Chance to gain +2 movement.', description: 'Premium routes occasionally speed conquest.' }),
    Object.freeze({ name: 'Airport', category: 'Special', price: 360, income: 110, passive: 'Warp tiles move forward instead of back.', description: 'Air routes convert risk into speed.' }),
    Object.freeze({ name: 'Bank', category: 'Special', price: 330, income: 95, passive: 'Settlement money gains interest.', description: 'Capital compounds between regions.' }),
    Object.freeze({ name: 'Laboratory', category: 'Special', price: 340, income: 90, passive: 'Attack increases after each boss.', description: 'Research improves combat tempo.' }),
    Object.freeze({ name: 'Casino', category: 'Special', price: 310, income: 88, passive: 'Luck improves event and treasure results.', description: 'Risk expertise bends randomness.' }),
    Object.freeze({ name: 'Harbor', category: 'Special', price: 320, income: 92, passive: 'Property income is increased at settlement.', description: 'Trade routes scale all holdings.' })
  ])
});

const gameState = { phase: 'start', screen: 'title', regionIndex: CONFIG.startRegion, turn: 0, space: CONFIG.firstSpace, lastRoll: 0, pendingTile: null, inBoss: false, bossHP: 0, bossGuard: false, rank: '', messages: [], images: {}, buttons: [], board: [], defeatedBosses: 0, player: { HP: CONFIG.startHP, MaxHP: CONFIG.startHP, Attack: CONFIG.startAttack, Defense: CONFIG.startDefense, Luck: CONFIG.startLuck, Money: CONFIG.startMoney, TotalAssets: 0, TotalIncome: 0, OwnedProperties: [], Inventory: [] }, regionFlags: { rerolls: 0 } };

function safeArray(v) { return Array.isArray(v) ? v : []; }
function log(msg) { gameState.messages.unshift(String(msg || '')); gameState.messages = gameState.messages.slice(CONFIG.uiButtonStart, CONFIG.logLimit); }
function hasProperty(name) { return safeArray(gameState.player.OwnedProperties).some(p => p && p.name === name); }
function createImage(name, folder) { const img = new Image(); img.dataset.name = name; img.src = `assets/${folder}/${name}.png`; gameState.images[name] = img; return img; }
function safeDrawImage(ctx, image, x, y, w, h, label) { if (image && image.complete && image.naturalWidth) ctx.drawImage(image, x, y, w, h); else { ctx.fillStyle = '#334155'; ctx.fillRect(x, y, w, h); ctx.strokeStyle = '#64748b'; ctx.strokeRect(x, y, w, h); ctx.fillStyle = CONFIG.colors.text; ctx.fillText(label || 'asset', x + CONFIG.tileGap, y + h / 2); } }
function randInt(min, max) { return Math.floor(Math.random() * (max - min + CONFIG.randomInclusiveOffset)) + min; }
function chooseWeighted(weights) { const entries = Object.entries(weights); const total = entries.reduce((a, e) => a + e[1], 0); let r = Math.random() * total; for (const [k, v] of entries) { if ((r -= v) <= 0) return k; } return entries[0][0]; }
function availableProperty() { const owned = new Set(gameState.player.OwnedProperties.map(p => p.name)); const list = CONFIG.properties.filter(p => !owned.has(p.name)); return list[randInt(CONFIG.uiButtonStart, Math.max(CONFIG.uiButtonStart, list.length - 1))] || null; }
function recomputeTotals() { const income = gameState.player.OwnedProperties.reduce((a, p) => a + (p ? p.income : CONFIG.uiButtonStart), CONFIG.uiButtonStart); gameState.player.TotalIncome = Math.round(income * (hasProperty('Harbor') ? 1 + CONFIG.harborIncomeBonusRate : 1)); gameState.player.TotalAssets = gameState.player.OwnedProperties.reduce((a, p) => a + (p ? p.price * CONFIG.assetOwnedMultiplier : CONFIG.uiButtonStart), gameState.player.Money); }
function resetRegionFlags() { gameState.regionFlags = { rerolls: hasProperty('Hotel') ? CONFIG.hotelRerolls : CONFIG.uiButtonStart }; }
function generateBoard() { const len = randInt(CONFIG.boardMin, CONFIG.boardMax); const board = [{ type: 'Start' }]; for (let i = 1; i < len - 1; i++) board.push({ type: chooseWeighted(CONFIG.tileWeights), property: null }); board.push({ type: 'Boss' }); let branches = randInt(CONFIG.branchMin, CONFIG.branchMax); for (let i = 1; i < board.length - 1 && branches > CONFIG.uiButtonStart; i++) if (board[i].type === 'Branch') branches--; recomputeTotals(); return board; }
function startGame() { Object.assign(gameState, { phase: 'playing', screen: 'board', regionIndex: CONFIG.startRegion, turn: 0, space: CONFIG.firstSpace, defeatedBosses: 0, rank: '', messages: [], board: [] }); Object.assign(gameState.player, { HP: CONFIG.startHP, MaxHP: CONFIG.startHP, Attack: CONFIG.startAttack, Defense: CONFIG.startDefense, Luck: CONFIG.startLuck, Money: CONFIG.startMoney, TotalAssets: 0, TotalIncome: 0, OwnedProperties: [], Inventory: [] }); gameState.board = generateBoard(); resetRegionFlags(); log('New company founded. Conquer every region efficiently.'); }
function rollDie() { let roll = randInt(CONFIG.diceMin, CONFIG.diceMax); if (hasProperty('Farm')) roll = Math.max(roll, CONFIG.farmMinRoll); if (hasProperty('Resort') && Math.random() < CONFIG.resortChance) roll += CONFIG.resortBonusMove; gameState.lastRoll = roll; return roll; }
function startTurn() { if (gameState.phase !== 'playing' || gameState.inBoss) return; gameState.turn++; if (hasProperty('Hot Spring')) gameState.player.HP = Math.min(gameState.player.MaxHP, gameState.player.HP + CONFIG.minDamage); if (hasProperty('Power Plant') && Math.random() < CONFIG.powerPlantItemChance) gameState.player.Inventory.push('Potion'); const roll = rollDie(); gameState.space = Math.min(gameState.board.length - 1, gameState.space + roll); resolveTile(gameState.board[gameState.space]); }
function reroll() { if ((gameState.regionFlags.rerolls || 0) <= 0 || gameState.inBoss) return; gameState.regionFlags.rerolls--; gameState.space = Math.max(CONFIG.firstSpace, gameState.space - gameState.lastRoll); log('Hotel reroll used.'); startTurn(); }
function resolveTile(tile) { const type = tile && tile.type; if (type === 'Town') { gameState.pendingTile = { action: 'buy', property: availableProperty() }; log('Town property offered.'); } else if (type === 'Shop') { gameState.pendingTile = { action: 'shop' }; log('Shop found.'); } else if (type === 'Inn') { gameState.pendingTile = { action: 'inn' }; log('Inn available.'); } else if (type === 'Event') eventTile(); else if (type === 'Treasure') treasureTile(); else if (type === 'Money') moneyTile(); else if (type === 'Warp') warpTile(); else if (type === 'Branch') branchTile(); else if (type === 'Boss') beginBoss(); }
function eventTile() { const good = randInt(CONFIG.diceMin, CONFIG.diceMax) + gameState.player.Luck + (hasProperty('Casino') ? CONFIG.casinoLuckBonus : CONFIG.uiButtonStart) >= CONFIG.eventGoodLuckTarget; if (good) { const heal = CONFIG.eventHeal + (hasProperty('Orchard') ? CONFIG.eventHeal : CONFIG.uiButtonStart); gameState.player.HP = Math.min(gameState.player.MaxHP, gameState.player.HP + heal); log('Good event healed HP.'); } else { const dmg = Math.max(CONFIG.minDamage, CONFIG.eventDamage - (hasProperty('Restaurant') ? gameState.player.Defense : CONFIG.uiButtonStart)); gameState.player.HP -= dmg; log('Bad event caused damage.'); } }
function treasureTile() { const gain = randInt(CONFIG.treasureMin, CONFIG.treasureMax) + gameState.player.Luck * CONFIG.bossAttackVariance; gameState.player.Money += gain; log(`Treasure gained $${gain}.`); }
function moneyTile() { const gain = CONFIG.moneyTileReward * (hasProperty('Theme Park') ? CONFIG.bossAttackVariance : CONFIG.minDamage); gameState.player.Money += gain; log(`Money tile paid $${gain}.`); }
function warpTile() { const move = randInt(CONFIG.minDamage, CONFIG.warpMaxBack); gameState.space = hasProperty('Airport') ? Math.min(gameState.board.length - 1, gameState.space + move) : Math.max(CONFIG.firstSpace, gameState.space - move); log('Warp changed your route.'); }
function branchTile() { const skip = randInt(CONFIG.minDamage, CONFIG.branchMax); gameState.space = Math.min(gameState.board.length - 1, gameState.space + skip); log('Branch shortcut selected.'); }
function buyProperty() { const p = gameState.pendingTile && gameState.pendingTile.property; if (!p || gameState.player.Money < p.price) return log('Not enough money.'); gameState.player.Money -= p.price; gameState.player.OwnedProperties.push(p); recomputeTotals(); resetRegionFlags(); gameState.pendingTile = null; log(`${p.name} purchased: ${p.passive}`); }
function shopBuy() { const cost = Math.round(CONFIG.shopItemCost * (hasProperty('Factory') ? CONFIG.guardReduction : CONFIG.minDamage)); if (gameState.player.Money >= cost) { gameState.player.Money -= cost; gameState.player.Inventory.push('Potion'); log('Potion purchased.'); } }
function innRest() { if (gameState.player.Money >= CONFIG.innCost) { gameState.player.Money -= CONFIG.innCost; gameState.player.HP = Math.min(gameState.player.MaxHP, gameState.player.HP + CONFIG.innHeal + (hasProperty('Ramen Shop') ? CONFIG.innHeal : CONFIG.uiButtonStart)); log('Rested at inn.'); } }
function beginBoss() { const b = CONFIG.regions[gameState.regionIndex].boss; gameState.inBoss = true; gameState.bossHP = b.hp; if (hasProperty('Steel Mill')) gameState.player.Defense += CONFIG.minDamage; log(`${b.name} challenged you.`); }
function bossCommand(cmd) { if (!gameState.inBoss) return; const b = CONFIG.regions[gameState.regionIndex].boss; if (cmd === 'Item') { const i = gameState.player.Inventory.indexOf('Potion'); if (i >= CONFIG.uiButtonStart) { gameState.player.Inventory.splice(i, 1); gameState.player.HP = Math.min(gameState.player.MaxHP, gameState.player.HP + CONFIG.potionHeal); } } else if (cmd === 'Guard') { gameState.bossGuard = true; if (hasProperty('Cafe')) gameState.player.Money += CONFIG.innCost; } else { gameState.bossHP -= Math.max(CONFIG.minDamage, gameState.player.Attack - b.defense); }
  if (gameState.bossHP <= CONFIG.uiButtonStart) return defeatBoss();
  const raw = Math.max(CONFIG.minDamage, b.attack + randInt(CONFIG.uiButtonStart, CONFIG.bossAttackVariance) - gameState.player.Defense); gameState.player.HP -= Math.ceil(raw * (gameState.bossGuard ? CONFIG.guardReduction : CONFIG.minDamage)); gameState.bossGuard = false; if (gameState.player.HP <= CONFIG.uiButtonStart) { gameState.phase = 'gameover'; gameState.screen = 'gameover'; log('Bankruptcy! Game over.'); } }
function defeatBoss() { gameState.inBoss = false; gameState.defeatedBosses++; if (hasProperty('Ranch')) gameState.player.HP = Math.min(gameState.player.MaxHP, gameState.player.HP + CONFIG.innHeal); if (hasProperty('Laboratory')) gameState.player.Attack += CONFIG.laboratoryAttackBonus; settlement(); }
function settlement() { recomputeTotals(); let income = gameState.player.TotalIncome; if (hasProperty('Bank')) income += Math.round(income * CONFIG.bankMoneyBonusRate); gameState.player.Money += income; recomputeTotals(); log(`Settlement paid $${income}.`); if (gameState.regionIndex >= CONFIG.finalBossIndex) return finishGame(); gameState.regionIndex++; gameState.space = CONFIG.firstSpace; gameState.board = generateBoard(); resetRegionFlags(); gameState.pendingTile = null; log(`Advanced to ${CONFIG.regions[gameState.regionIndex].name}.`); }
function finishGame() { const scoreTurns = gameState.turn - Math.floor(gameState.player.TotalAssets / CONFIG.scoreAssetDivisor) - Math.floor(gameState.player.TotalIncome / CONFIG.scoreIncomeDivisor) - gameState.defeatedBosses * CONFIG.scoreBossBonus; gameState.rank = scoreTurns <= CONFIG.rankSS ? 'SS' : scoreTurns <= CONFIG.rankS ? 'S' : scoreTurns <= CONFIG.rankA ? 'A' : scoreTurns <= CONFIG.rankB ? 'B' : scoreTurns <= CONFIG.rankC ? 'C' : 'D'; gameState.phase = 'gameover'; gameState.screen = 'victory'; log(`Victory! Rank ${gameState.rank}.`); }
function saveGame() { localStorage.setItem('regionalTycoonSave', JSON.stringify(gameState)); log('Saved.'); }
function loadGame() { const raw = localStorage.getItem('regionalTycoonSave'); if (!raw) return; const data = JSON.parse(raw); Object.assign(gameState, data); log('Loaded.'); }
function update() { recomputeTotals(); if (gameState.player.HP <= CONFIG.uiButtonStart && gameState.phase === 'playing') { gameState.phase = 'gameover'; gameState.screen = 'gameover'; } }
function button(label, action) { gameState.buttons.push({ label, action }); }
function render(ctx) { gameState.buttons = []; ctx.clearRect(CONFIG.uiButtonStart, CONFIG.uiButtonStart, CONFIG.canvasWidth, CONFIG.canvasHeight); ctx.fillStyle = CONFIG.colors.bg; ctx.fillRect(CONFIG.uiButtonStart, CONFIG.uiButtonStart, CONFIG.canvasWidth, CONFIG.canvasHeight); ctx.fillStyle = CONFIG.colors.text; ctx.font = '16px sans-serif'; safeDrawImage(ctx, gameState.images.ui_button_shop, CONFIG.uiImageX, CONFIG.uiImageY, CONFIG.uiImageW, CONFIG.uiImageH, 'UI'); ctx.fillText(`Region: ${CONFIG.regions[gameState.regionIndex]?.name || '-'}`, CONFIG.hudX, CONFIG.hudY1); ctx.fillText(`Turn ${gameState.turn} HP ${gameState.player.HP}/${gameState.player.MaxHP} $${gameState.player.Money}`, CONFIG.hudX, CONFIG.hudY2); ctx.fillText(`Income ${gameState.player.TotalIncome} Assets ${gameState.player.TotalAssets} Bosses ${gameState.defeatedBosses}`, CONFIG.hudX, CONFIG.hudY3); gameState.board.forEach((t, i) => { const x = CONFIG.boardX + (i % CONFIG.boardColumns) * (CONFIG.tileSize + CONFIG.tileGap); const y = CONFIG.boardY + Math.floor(i / CONFIG.boardColumns) * (CONFIG.tileSize + CONFIG.tileGap); ctx.fillStyle = i === gameState.space ? CONFIG.colors.player : '#1e293b'; ctx.fillRect(x, y, CONFIG.tileSize, CONFIG.tileSize); ctx.fillStyle = CONFIG.colors.text; ctx.fillText((t?.type || '?').slice(CONFIG.uiButtonStart, CONFIG.bossAttackVariance), x + CONFIG.textPad, y + CONFIG.tileTextY); }); ctx.fillText(`Properties: ${gameState.player.OwnedProperties.map(p => p.name).join(', ') || 'none'}`, CONFIG.hudX, CONFIG.propertyTextY); ctx.fillText(gameState.messages.join(' | '), CONFIG.hudX, CONFIG.messageTextY); if (gameState.phase === 'start') button('New Game', startGame); else if (gameState.inBoss) { button('Attack', () => bossCommand('Attack')); button('Guard', () => bossCommand('Guard')); button('Item', () => bossCommand('Item')); } else if (gameState.phase === 'playing') { button('Roll / Move', startTurn); if (gameState.regionFlags.rerolls > CONFIG.uiButtonStart) button('Hotel Reroll', reroll); if (gameState.pendingTile?.action === 'buy') button(`Buy ${gameState.pendingTile.property?.name || 'Property'}`, buyProperty); if (gameState.pendingTile?.action === 'shop') button('Buy Potion', shopBuy); if (gameState.pendingTile?.action === 'inn') button('Rest', innRest); button('Save', saveGame); button('Load', loadGame); } else button('New Game', startGame); ctx.fillText(gameState.screen === 'victory' ? `Final Rank: ${gameState.rank}` : '', CONFIG.rankX, CONFIG.rankY); drawButtons(); }
function drawButtons() { const panel = document.getElementById('controls'); if (!panel) return; panel.innerHTML = ''; gameState.buttons.forEach(b => { const el = document.createElement('button'); el.textContent = b.label; el.onclick = b.action; panel.appendChild(el); }); const logPanel = document.getElementById('log'); if (logPanel) logPanel.textContent = gameState.messages.join('\n'); }
function boot() { ['property_farm_icon', 'boss_fire_idle', 'ui_button_shop'].forEach((n, i) => createImage(n, i === 1 ? 'bosses' : i === 2 ? 'ui' : 'properties')); const canvas = document.getElementById('gameCanvas'); if (!canvas) return; const ctx = canvas.getContext('2d'); setInterval(() => { update(); render(ctx); }, 1000 / CONFIG.frameRate); }
if (typeof window !== 'undefined') window.addEventListener('load', boot);
if (typeof module !== 'undefined') module.exports = { CONFIG, gameState, startGame, startTurn, buyProperty, bossCommand, update, generateBoard, settlement, finishGame, hasProperty, createImage, safeDrawImage };
